name: Generate Pydoc
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc
      - name: Generate Docs
        env:
          # Le decimos a Django dónde está la configuración para que no proteste al importar los módulos
          DJANGO_SETTINGS_MODULE: my_site.settings
        run: |
          # Añadimos el directorio actual al PATH de Python para que encuentre 'blog' y 'my_site'
          export PYTHONPATH="${PYTHONPATH}:${PWD}"
          # Ejecutamos pdoc apuntando a tus carpetas de código
          pdoc -o docs blog my_site manage.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
